apiVersion: apps/v1
kind: Deployment
metadata:
  name: lexo-api-deployment
  namespace: lexo-api
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: lexo-api
  template:
    metadata:
      labels:
        app: lexo-api
    spec:
      containers:
        - name: lexo-api
          image: lemonware/lexo-api:main
          ports:
            - containerPort: 3006
          env:
            - name: MIKRO_ORM_DB_USER
              valueFrom:
                secretKeyRef:
                  name: lexo-api-db-secrets
                  key: db-user
            - name: MIKRO_ORM_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: lexo-api-db-secrets
                  key: db-password
            - name: MIKRO_ORM_DB_NAME
              value: lexo-db
            - name: MIKRO_ORM_DB_PORT
              value: "5432"
            - name: MIKRO_ORM_DB_HOST
              value: lexo-db-service
            - name: API_BASE_URL
              value: "https://lexo-api.lemonware.dev"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: lexo-api-secrets
                  key: jwt-secret
            - name: ADMIN_CREATION_KEY
              valueFrom:
                secretKeyRef:
                  name: lexo-api-secrets
                  key: admin-creation-key
            - name: DOCKERHUB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: lexo-api-secrets
                  key: dockerhub-username
            - name: DOCKERHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: lexo-api-secrets
                  key: dockerhub-token
            - name: DOCKERHUB_CONTAINER_NAME
              value: lexo-api
            - name: DOCKERHUB_WEBHOOK_TOKEN
              valueFrom:
                secretKeyRef:
                  name: lexo-api-secrets
                  key: dockerhub-webhook-token
          livenessProbe:
            httpGet:
              path: /
              port: 3006
            initialDelaySeconds: 30
            periodSeconds: 10
          imagePullPolicy: Always
      imagePullSecrets:
        - name: lexo-api-registry-credentials
