apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: lexo-api
  name: deployment-manager
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "update"]